//! Multilingual support for the Cheungfun RAG framework
//!
//! This module provides comprehensive multilingual capabilities including:
//! - Language detection using lingua-rs
//! - Language-specific configuration management
//! - Cross-language query processing
//! - Multilingual content handling

pub mod language_config;
pub mod language_detector;
pub mod multilingual_processor;

#[cfg(test)]
mod simple_test;

pub use language_config::*;
pub use language_detector::*;
pub use multilingual_processor::*;

use serde::{Deserialize, Serialize};
use std::fmt;

/// Supported languages in the Cheungfun framework
///
/// This enum represents the languages that are officially supported
/// by the framework, with comprehensive language detection and processing capabilities.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(missing_docs)] // TODO: Add documentation for each language variant
pub enum SupportedLanguage {
    // Major world languages
    English,
    Chinese,
    Japanese,
    Korean,
    Spanish,
    French,
    German,
    Russian,
    Portuguese,
    Italian,
    Arabic,
    Hindi,
    Vietnamese,
    Thai,
    Indonesian,
    Malay,

    // European languages
    Dutch,
    Swedish,
    Norwegian,
    Danish,
    Finnish,
    Polish,
    Czech,
    Slovak,
    Hungarian,
    Romanian,
    Bulgarian,
    Croatian,
    Serbian,
    Slovenian,
    Estonian,
    Latvian,
    Lithuanian,
    Ukrainian,
    Belarusian,
    Turkish,
    Greek,
    Hebrew,

    // Middle Eastern and South Asian languages
    Persian,
    Urdu,
    Bengali,
    Gujarati,
    Punjabi,
    Tamil,
    Telugu,
    Marathi,

    // Other languages
    Nepali,
    Sinhala,
    Burmese,
    Khmer,
    Lao,
    Georgian,
    Armenian,
    Azerbaijani,
    Kazakh,
    Kyrgyz,
    Mongolian,
    Uzbek,
    Tajik,
    Pashto,
    Sindhi,
    Albanian,
    Basque,
    Catalan,
    Galician,
    Irish,
    Welsh,
    ScottishGaelic,
    Icelandic,
    Faroese,
    Maltese,
    Luxembourgish,
    Afrikaans,
    Zulu,
    Xhosa,
    Swahili,
    Yoruba,
    Igbo,
    Hausa,
    Amharic,
    Oromo,
    Somali,
    Malagasy,
}

impl SupportedLanguage {
    /// Get the ISO 639-1 language code
    pub fn iso_code(&self) -> &'static str {
        match self {
            Self::English => "en",
            Self::Chinese => "zh",
            Self::Japanese => "ja",
            Self::Korean => "ko",
            Self::Spanish => "es",
            Self::French => "fr",
            Self::German => "de",
            Self::Russian => "ru",
            Self::Portuguese => "pt",
            Self::Italian => "it",
            Self::Arabic => "ar",
            Self::Hindi => "hi",
            Self::Vietnamese => "vi",
            Self::Thai => "th",
            Self::Indonesian => "id",
            Self::Malay => "ms",
            Self::Dutch => "nl",
            Self::Swedish => "sv",
            Self::Norwegian => "no",
            Self::Danish => "da",
            Self::Finnish => "fi",
            Self::Polish => "pl",
            Self::Czech => "cs",
            Self::Slovak => "sk",
            Self::Hungarian => "hu",
            Self::Romanian => "ro",
            Self::Bulgarian => "bg",
            Self::Croatian => "hr",
            Self::Serbian => "sr",
            Self::Slovenian => "sl",
            Self::Estonian => "et",
            Self::Latvian => "lv",
            Self::Lithuanian => "lt",
            Self::Ukrainian => "uk",
            Self::Belarusian => "be",
            Self::Turkish => "tr",
            Self::Greek => "el",
            Self::Hebrew => "he",
            Self::Persian => "fa",
            Self::Urdu => "ur",
            Self::Bengali => "bn",
            Self::Gujarati => "gu",
            Self::Punjabi => "pa",
            Self::Tamil => "ta",
            Self::Telugu => "te",
            Self::Marathi => "mr",
            Self::Nepali => "ne",
            Self::Sinhala => "si",
            Self::Burmese => "my",
            Self::Khmer => "km",
            Self::Lao => "lo",
            Self::Georgian => "ka",
            Self::Armenian => "hy",
            Self::Azerbaijani => "az",
            Self::Kazakh => "kk",
            Self::Kyrgyz => "ky",
            Self::Mongolian => "mn",
            Self::Uzbek => "uz",
            Self::Tajik => "tg",
            Self::Pashto => "ps",
            Self::Sindhi => "sd",
            Self::Albanian => "sq",
            Self::Basque => "eu",
            Self::Catalan => "ca",
            Self::Galician => "gl",
            Self::Irish => "ga",
            Self::Welsh => "cy",
            Self::ScottishGaelic => "gd",
            Self::Icelandic => "is",
            Self::Faroese => "fo",
            Self::Maltese => "mt",
            Self::Luxembourgish => "lb",
            Self::Afrikaans => "af",
            Self::Zulu => "zu",
            Self::Xhosa => "xh",
            Self::Swahili => "sw",
            Self::Yoruba => "yo",
            Self::Igbo => "ig",
            Self::Hausa => "ha",
            Self::Amharic => "am",
            Self::Oromo => "om",
            Self::Somali => "so",
            Self::Malagasy => "mg",
        }
    }

    /// Get the human-readable language name
    pub fn name(&self) -> &'static str {
        match self {
            Self::English => "English",
            Self::Chinese => "Chinese (中文)",
            Self::Japanese => "Japanese (日本語)",
            Self::Korean => "Korean (한국어)",
            Self::Spanish => "Spanish (Español)",
            Self::French => "French (Français)",
            Self::German => "German (Deutsch)",
            Self::Russian => "Russian (Русский)",
            Self::Portuguese => "Portuguese (Português)",
            Self::Italian => "Italian (Italiano)",
            Self::Arabic => "Arabic (العربية)",
            Self::Hindi => "Hindi (हिन्दी)",
            Self::Vietnamese => "Vietnamese (Tiếng Việt)",
            Self::Thai => "Thai (ไทย)",
            Self::Indonesian => "Indonesian (Bahasa Indonesia)",
            Self::Malay => "Malay (Bahasa Melayu)",
            Self::Dutch => "Dutch (Nederlands)",
            Self::Swedish => "Swedish (Svenska)",
            Self::Norwegian => "Norwegian (Norsk)",
            Self::Danish => "Danish (Dansk)",
            Self::Finnish => "Finnish (Suomi)",
            Self::Polish => "Polish (Polski)",
            Self::Czech => "Czech (Čeština)",
            Self::Slovak => "Slovak (Slovenčina)",
            Self::Hungarian => "Hungarian (Magyar)",
            Self::Romanian => "Romanian (Română)",
            Self::Bulgarian => "Bulgarian (Български)",
            Self::Croatian => "Croatian (Hrvatski)",
            Self::Serbian => "Serbian (Српски)",
            Self::Slovenian => "Slovenian (Slovenščina)",
            Self::Estonian => "Estonian (Eesti)",
            Self::Latvian => "Latvian (Latviešu)",
            Self::Lithuanian => "Lithuanian (Lietuvių)",
            Self::Ukrainian => "Ukrainian (Українська)",
            Self::Belarusian => "Belarusian (Беларуская)",
            Self::Turkish => "Turkish (Türkçe)",
            Self::Greek => "Greek (Ελληνικά)",
            Self::Hebrew => "Hebrew (עברית)",
            Self::Persian => "Persian (فارسی)",
            Self::Urdu => "Urdu (اردو)",
            Self::Bengali => "Bengali (বাংলা)",
            Self::Gujarati => "Gujarati (ગુજરાતી)",
            Self::Punjabi => "Punjabi (ਪੰਜਾਬੀ)",
            Self::Tamil => "Tamil (தமிழ்)",
            Self::Telugu => "Telugu (తెలుగు)",
            Self::Marathi => "Marathi (मराठी)",
            Self::Nepali => "Nepali (नेपाली)",
            Self::Sinhala => "Sinhala (සිංහල)",
            Self::Burmese => "Burmese (မြန်မာ)",
            Self::Khmer => "Khmer (ខ្មែរ)",
            Self::Lao => "Lao (ລາວ)",
            Self::Georgian => "Georgian (ქართული)",
            Self::Armenian => "Armenian (Հայերեն)",
            Self::Azerbaijani => "Azerbaijani (Azərbaycan)",
            Self::Kazakh => "Kazakh (Қазақ)",
            Self::Kyrgyz => "Kyrgyz (Кыргыз)",
            Self::Mongolian => "Mongolian (Монгол)",
            Self::Uzbek => "Uzbek (Oʻzbek)",
            Self::Tajik => "Tajik (Тоҷикӣ)",
            Self::Pashto => "Pashto (پښتو)",
            Self::Sindhi => "Sindhi (سنڌي)",
            Self::Albanian => "Albanian (Shqip)",
            Self::Basque => "Basque (Euskera)",
            Self::Catalan => "Catalan (Català)",
            Self::Galician => "Galician (Galego)",
            Self::Irish => "Irish (Gaeilge)",
            Self::Welsh => "Welsh (Cymraeg)",
            Self::ScottishGaelic => "Scottish Gaelic (Gàidhlig)",
            Self::Icelandic => "Icelandic (Íslenska)",
            Self::Faroese => "Faroese (Føroyskt)",
            Self::Maltese => "Maltese (Malti)",
            Self::Luxembourgish => "Luxembourgish (Lëtzebuergesch)",
            Self::Afrikaans => "Afrikaans",
            Self::Zulu => "Zulu (isiZulu)",
            Self::Xhosa => "Xhosa (isiXhosa)",
            Self::Swahili => "Swahili (Kiswahili)",
            Self::Yoruba => "Yoruba (Yorùbá)",
            Self::Igbo => "Igbo (Asụsụ Igbo)",
            Self::Hausa => "Hausa (Harshen Hausa)",
            Self::Amharic => "Amharic (አማርኛ)",
            Self::Oromo => "Oromo (Afaan Oromoo)",
            Self::Somali => "Somali (Soomaali)",
            Self::Malagasy => "Malagasy (Malagasy)",
        }
    }

    /// Create from ISO 639-1 language code
    pub fn from_iso_code(code: &str) -> Option<Self> {
        match code.to_lowercase().as_str() {
            "en" => Some(Self::English),
            "zh" => Some(Self::Chinese),
            "ja" => Some(Self::Japanese),
            "ko" => Some(Self::Korean),
            "es" => Some(Self::Spanish),
            "fr" => Some(Self::French),
            "de" => Some(Self::German),
            "ru" => Some(Self::Russian),
            "pt" => Some(Self::Portuguese),
            "it" => Some(Self::Italian),
            "ar" => Some(Self::Arabic),
            "hi" => Some(Self::Hindi),
            "vi" => Some(Self::Vietnamese),
            "th" => Some(Self::Thai),
            "id" => Some(Self::Indonesian),
            "ms" => Some(Self::Malay),
            _ => None,
        }
    }

    /// Get all supported languages
    pub fn all() -> Vec<Self> {
        vec![
            Self::English,
            Self::Chinese,
            Self::Japanese,
            Self::Korean,
            Self::Spanish,
            Self::French,
            Self::German,
            Self::Russian,
            Self::Portuguese,
            Self::Italian,
            Self::Arabic,
            Self::Hindi,
            Self::Vietnamese,
            Self::Thai,
            Self::Indonesian,
            Self::Malay,
            Self::Dutch,
            Self::Swedish,
            Self::Norwegian,
            Self::Danish,
            Self::Finnish,
            Self::Polish,
            Self::Czech,
            Self::Slovak,
            Self::Hungarian,
            Self::Romanian,
            Self::Bulgarian,
            Self::Croatian,
            Self::Serbian,
            Self::Slovenian,
            Self::Estonian,
            Self::Latvian,
            Self::Lithuanian,
            Self::Ukrainian,
            Self::Belarusian,
            Self::Turkish,
            Self::Greek,
            Self::Hebrew,
            Self::Persian,
            Self::Urdu,
            Self::Bengali,
            Self::Gujarati,
            Self::Punjabi,
            Self::Tamil,
            Self::Telugu,
            Self::Marathi,
            Self::Nepali,
            Self::Sinhala,
            Self::Burmese,
            Self::Khmer,
            Self::Lao,
            Self::Georgian,
            Self::Armenian,
            Self::Azerbaijani,
            Self::Kazakh,
            Self::Kyrgyz,
            Self::Mongolian,
            Self::Uzbek,
            Self::Tajik,
            Self::Pashto,
            Self::Sindhi,
            Self::Albanian,
            Self::Basque,
            Self::Catalan,
            Self::Galician,
            Self::Irish,
            Self::Welsh,
            Self::ScottishGaelic,
            Self::Icelandic,
            Self::Faroese,
            Self::Maltese,
            Self::Luxembourgish,
            Self::Afrikaans,
            Self::Zulu,
            Self::Xhosa,
            Self::Swahili,
            Self::Yoruba,
            Self::Igbo,
            Self::Hausa,
            Self::Amharic,
            Self::Oromo,
            Self::Somali,
            Self::Malagasy,
        ]
    }
}

impl fmt::Display for SupportedLanguage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

impl Default for SupportedLanguage {
    fn default() -> Self {
        Self::English
    }
}
