[package]
name = "cheungfun-examples"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
description = "Examples for the Cheungfun RAG framework"
categories.workspace = true

[dependencies]
cheungfun = { path = "../cheungfun" }
cheungfun-core = { path = "../cheungfun-core" }
cheungfun-indexing = { path = "../cheungfun-indexing" }
cheungfun-query = { path = "../cheungfun-query" }
cheungfun-integrations = { path = "../cheungfun-integrations" }

# Core async
tokio = { workspace = true }
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Additional dependencies
uuid = { workspace = true }
siumai = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.20"

[features]
default = []

# Feature for Candle embedder examples
candle = ["cheungfun-integrations/candle"]

# Feature for FastEmbed examples
fastembed = ["cheungfun-integrations/fastembed"]

# All embedding features
all-embedders = ["candle", "fastembed"]

[[bin]]
name = "basic_usage"
path = "src/basic_usage.rs"

[[bin]]
name = "end_to_end_indexing"
path = "end_to_end_indexing.rs"

[[bin]]
name = "end_to_end_query"
path = "end_to_end_query.rs"

[[bin]]
name = "end_to_end_retrieval_demo"
path = "end_to_end_retrieval_demo.rs"

[[bin]]
name = "complete_rag_demo"
path = "complete_rag_demo.rs"

[[bin]]
name = "candle_embedder_demo"
path = "candle_embedder_demo.rs"
required-features = ["candle"]

[[bin]]
name = "qdrant_vector_store_demo"
path = "src/qdrant_vector_store_demo.rs"
