[package]
name = "cheungfun-examples"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
description = "Examples for the Cheungfun RAG framework"
categories.workspace = true

[dependencies]
cheungfun = { path = "../cheungfun" }
cheungfun-core = { path = "../cheungfun-core" }
cheungfun-indexing = { path = "../cheungfun-indexing" }
cheungfun-query = { path = "../cheungfun-query" }
cheungfun-integrations = { path = "../cheungfun-integrations" }

# Core async
tokio = { workspace = true }
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Additional dependencies
uuid = { workspace = true }
siumai = { workspace = true }

[features]
default = []

[[bin]]
name = "basic_usage"
path = "src/basic_usage.rs"

[[bin]]
name = "end_to_end_indexing"
path = "end_to_end_indexing.rs"

[[bin]]
name = "end_to_end_query"
path = "end_to_end_query.rs"

[[bin]]
name = "end_to_end_retrieval_demo"
path = "end_to_end_retrieval_demo.rs"
